name: check

# Runs `cargo check` whenever code is pushed or pr'd into master. 

on: 
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: actions-rs/cargo@v1
        with:
          command: check
